sample_profiles = [
    {
        "name": "Dr. Ananya Sharma",
        "position": "AI Research Scientist | AI Fundamentals Specialist",
        "company": "AI Solutions Ltd.",
        "location": "San Francisco, CA",
        "linkedin_summary": "Experienced AI professional focused on the fundamentals of Artificial Intelligence, building foundational models and training AI systems.",
        "skills": [
            "Artificial Intelligence Fundamentals",
            "AI Systems",
            "Machine Learning",
        ],
    },
    {
        "name": "John Doe",
        "position": "AI Developer | AI Framework Engineer",
        "company": "NextGen AI",
        "location": "Austin, TX",
        "linkedin_summary": "Developer with expertise in AI fundamentals, specializing in implementing AI frameworks for enterprise solutions.",
        "skills": ["AI Fundamentals", "Python", "TensorFlow", "AI Deployment"],
    },
    {
        "name": "Lisa Brown",
        "position": "AI Consultant | ML Fundamentals Specialist",
        "company": "AI Innovators Group",
        "location": "Toronto, Canada",
        "linkedin_summary": "AI consultant helping enterprises understand and adopt AI fundamentals for strategic growth.",
        "skills": [
            "AI Strategy",
            "Machine Learning Fundamentals",
            "Artificial Intelligence",
        ],
    },
    {
        "name": "Mohammed Khan",
        "position": "AI Fundamentals Trainer | Researcher",
        "company": "AI Education Hub",
        "location": "Dubai, UAE",
        "linkedin_summary": "Trainer and researcher focusing on teaching the foundational principles of Artificial Intelligence and its real-world applications.",
        "skills": ["AI Fundamentals", "Education", "AI Tools"],
    },
    {
        "name": "Michael Brown",
        "position": "Data Scientist | Knowledge Mining Expert",
        "company": "Insight Analytics",
        "location": "New York, NY",
        "linkedin_summary": "Data scientist specializing in AI-driven data analytics, knowledge mining, and predictive analytics.",
        "skills": ["Data Analytics", "Knowledge Mining", "Machine Learning"],
    },
    {
        "name": "Emily White",
        "position": "AI Data Analyst | Data Mining Specialist",
        "company": "DataWorks AI",
        "location": "London, UK",
        "linkedin_summary": "Focused on AI-powered data analytics and extracting meaningful insights through knowledge mining.",
        "skills": ["AI Data Analytics", "Data Mining", "SQL", "Python"],
    },
    {
        "name": "Rajesh Gupta",
        "position": "Senior Data Engineer | AI Data Analytics Lead",
        "company": "Analytics Pro",
        "location": "Bangalore, India",
        "linkedin_summary": "Leading AI analytics projects to discover actionable insights using advanced knowledge mining techniques.",
        "skills": ["AI Analytics", "Big Data", "ETL Pipelines", "Data Mining"],
    },
    {
        "name": "Sophia Martinez",
        "position": "AI Data Specialist | BI Analyst",
        "company": "BrightData AI",
        "location": "Sydney, Australia",
        "linkedin_summary": "Business intelligence analyst with a focus on AI-driven data analytics and knowledge extraction.",
        "skills": [
            "AI Data Analytics",
            "Knowledge Extraction",
            "BI Tools",
            "Visualization",
        ],
    },
    {
        "name": "James Kim",
        "position": "Generative AI Engineer | LLM Developer",
        "company": "GenAI Labs",
        "location": "Seoul, South Korea",
        "linkedin_summary": "AI engineer specializing in generative AI, creating cutting-edge models for text, image, and video generation.",
        "skills": ["Generative AI", "Large Language Models", "Text Generation", "NLP"],
    },
    {
        "name": "Isabella Cruz",
        "position": "AI Researcher | Generative Art Specialist",
        "company": "AI Creative Studio",
        "location": "Madrid, Spain",
        "linkedin_summary": "Combining creativity and AI to develop generative models that produce art, design, and interactive media.",
        "skills": ["Generative AI", "AI Art", "Deep Learning", "Python"],
    },
    {
        "name": "Nikhil Sharma",
        "position": "Generative AI Developer | ML Expert",
        "company": "AI Fusion Tech",
        "location": "Delhi, India",
        "linkedin_summary": "Developer of generative AI models for automating content generation and enhancing user experiences.",
        "skills": ["Generative AI", "Deep Learning", "Machine Learning", "AI Tools"],
    },
    {
        "name": "Hannah Lee",
        "position": "AI Specialist | Generative Model Engineer",
        "company": "GenTech AI",
        "location": "San Diego, CA",
        "linkedin_summary": "Building generative models to solve complex problems in design, content creation, and business automation.",
        "skills": ["Generative AI", "Content Automation", "Model Training", "NLP"],
    },
    {
        "name": "Peter Thompson",
        "position": "Machine Learning Engineer | Deep Learning Specialist",
        "company": "DeepAI Solutions",
        "location": "Boston, MA",
        "linkedin_summary": "Engineer focusing on developing deep learning models to solve advanced AI challenges.",
        "skills": ["Deep Learning", "Neural Networks", "AI Frameworks", "TensorFlow"],
    },
    {
        "name": "Fatima Al-Farsi",
        "position": "AI Scientist | ML and Deep Learning Researcher",
        "company": "AI Innovate Research",
        "location": "Abu Dhabi, UAE",
        "linkedin_summary": "AI scientist conducting research in machine learning and deep learning to improve AI model accuracy.",
        "skills": ["Deep Learning", "Machine Learning", "AI Research", "PyTorch"],
    },
    {
        "name": "Carlos Rodriguez",
        "position": "AI Engineer | Neural Networks Expert",
        "company": "AI Labs International",
        "location": "Mexico City, Mexico",
        "linkedin_summary": "AI engineer specializing in designing deep neural networks for image and speech recognition systems.",
        "skills": ["Neural Networks", "Deep Learning", "AI Systems", "Python"],
    },
    {
        "name": "Anna Petrova",
        "position": "Deep Learning Specialist | AI Model Developer",
        "company": "SmartAI Systems",
        "location": "Moscow, Russia",
        "linkedin_summary": "AI model developer with experience building deep learning pipelines for predictive analysis.",
        "skills": ["Deep Learning", "Model Deployment", "AI Training", "Data Science"],
    },
    {
        "name": "Ethan Green",
        "position": "AI Ethics Specialist | Responsible AI Advocate",
        "company": "Ethical AI Alliance",
        "location": "Berlin, Germany",
        "linkedin_summary": "Advocate for ethical AI practices, ensuring fairness, accountability, and transparency in AI systems.",
        "skills": ["Responsible AI", "AI Ethics", "Policy Development", "Governance"],
    },
    {
        "name": "Amara Okafor",
        "position": "AI Policy Analyst | Responsible AI Consultant",
        "company": "AI Ethics Advisory",
        "location": "Lagos, Nigeria",
        "linkedin_summary": "Consultant developing policies to ensure responsible AI development and deployment across organizations.",
        "skills": ["Responsible AI", "AI Policy", "Governance", "Transparency"],
    },
    {
        "name": "William Smith",
        "position": "Responsible AI Engineer | Fairness Auditor",
        "company": "TechEthics Solutions",
        "location": "Seattle, WA",
        "linkedin_summary": "Engineer auditing AI systems for fairness, ensuring alignment with responsible AI principles.",
        "skills": [
            "Responsible AI",
            "Bias Detection",
            "Fairness Audits",
            "AI Governance",
        ],
    },
    {
        "name": "Chen Wei",
        "position": "AI Ethics Researcher | Responsible AI Specialist",
        "company": "AI Integrity Labs",
        "location": "Shanghai, China",
        "linkedin_summary": "Researcher exploring responsible AI frameworks to ensure ethical AI adoption in diverse industries.",
        "skills": [
            "Responsible AI",
            "AI Frameworks",
            "Ethical Audits",
            "Policy Research",
        ],
    },
]
